version: '3.3'

services:
  mysqlDB:
    container_name: mysqlDB
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'scheduler'
      MYSQL_USER: 'root'
      MYSQL_ROOT_PASSWORD: 'mYsQl'
      MYSQL_TCP_PORT: 3307
    ports:
      - 3307:3307
    volumes:
      - /src/main/resources/db.changelog/init/create_shema_and_user.sql:/docker-entrypoint-initdb.d/0_init.sql 
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--sql-mode=ALLOW_INVALID_DATES','--default_time_zone=+00:00','--max_connections=1000' ]

  scheduler:
    image: scheduler
    container_name: scheduler-app
    ports:
      - "8770:8770"
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - "mysqlDB"